module.exports = {
  apps: [
    {
      name: 'mcp-api',
      script: 'dist/main.js',
      cwd: 'C:/Users/Administrator/Desktop/udp/backend',
      node_args: '--env-file=.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: { NODE_ENV: 'production', RUN_MIGRATIONS: 'true' },
      error_file: 'C:/mcp-data/api-err.log',
      out_file: 'C:/mcp-data/api.log',
      merge_logs: true,
    },
    {
      name: 'mcp-worker',
      script: 'dist/worker.main.js',
      cwd: 'C:/Users/Administrator/Desktop/udp/backend',
      node_args: '--env-file=.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: { NODE_ENV: 'production' },
      error_file: 'C:/mcp-data/worker-err.log',
      out_file: 'C:/mcp-data/worker.log',
      merge_logs: true,
    },
    {
      name: 'mcp-scheduler',
      script: 'dist/scheduler.main.js',
      cwd: 'C:/Users/Administrator/Desktop/udp/backend',
      node_args: '--env-file=.env',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '128M',
      env: { NODE_ENV: 'production' },
      error_file: 'C:/mcp-data/scheduler-err.log',
      out_file: 'C:/mcp-data/scheduler.log',
      merge_logs: true,
    },
  ],
};
